version: '3.8'
services:
  bluelog:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - ENV=development
      - PYTHONPATH=/app
      - HTTP_PROXY=http://127.0.0.1:7890
      - HTTPS_PROXY=https://127.0.0.1:7890
    env_file:
      - .flaskenv
    command: python run.py
    restart: always
    networks:
      - bluelog_network
networks:
  bluelog_network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.0/16"
