version: '3.8'
services:
  bluelog:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - ENV=development
    command: python bluelog.py
    restart: always
    networks:
      - bluelog_network
networks:
  bluelog_network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.0/16"
